"""added some columns to facility table

Revision ID: d57c592a21a3
Revises: faf9573d0c6b
Create Date: 2026-01-30 13:24:32.504870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57c592a21a3'
down_revision = 'faf9573d0c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('incharge_name', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_column('incharge_name')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
